
services:
  propiedades360:
    build: Propiedades360
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://prop360:3306/propiedades360?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: contrasenia
    restart: always
    depends_on:
      prop360:
          condition: service_healthy
  prop360:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD: contrasenia
      MYSQL_DATABASE: propiedades360
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10